[project]
name = "2025-04-20-mcp-test"
version = "0.1.0"
description = "Building out MCP tutorials"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.6.0",
    "mcp-cli>=0.1.0",
    "nest-asyncio>=1.6.0",
    "pandas>=2.2.3",
]
